FROM python:3.10
RUN git clone https://github.com/DamienSALEM/M4-annual-project-handwritten-digits-recognition.git
WORKDIR /M4-annual-project-handwritten-digits-recognition
COPY ./requirements.txt ./
RUN pip install -r requirements.txt
RUN pip install tensorflow
RUN pip install python-dotenv
RUN pip install django-cors-headers
COPY ./.env /M4-annual-project-handwritten-digits-recognition
WORKDIR /M4-annual-project-handwritten-digits-recognition/API/backend

EXPOSE 8000
CMD [ "python", "manage.py","runserver" ,"0.0.0.0:8000"]